### ISSUE TITLE
Use aw-fakedata to generate notebook and publish to gh-pages

### ISSUE THREAD

**Issue by ErikBjare** [ErikBjare/quantifiedme#2]
Would finally make the notebook ready for viewing.

### TODO

 - [ ] Add GitHub Actions CI config
   - [ ] Add mypy checking
   - [ ] Add pytest run (with coverage and nbval)
 - [ ] Generate notebook in CI
 - [ ] Deploy notebook to gh-pages
 - [ ] Merge the fakedata generation in https://github.com/ErikBjare/quantifiedme/blob/master/src/quantifiedme/activitywatch.py with aw-fakedata
